openapi: 3.0.0
info:
  title: Your API
  version: 1.0.0

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth: [] # Use the BasicAuth scheme for all operations

paths:
  /oauth/token:
    post:
      summary: Get OAuth2 Token
      security:
        - BasicAuth: [] # Use BasicAuth for this specific operation
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  expires_in:
                    type: integer
                  refresh_token:
                    type: string
                  scope:
                    type: string